apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: sandbox
spec:
  template:
    spec:
      repository: 44smkn/sandbox
      labels:
        - sandbox
      image: public.ecr.aws/z8o9m4l5/system-components/mirrors/summerwind/actions-runner-dind:v2.283.3-ubuntu-20.04
      imagePullPolicy: IfNotPresent
      dockerdWithinRunnerContainer: true
      serviceAccountName: sandbox
      securityContext:
        fsGroup: 1447
      ephemeral: false
      tolerations:
        - key: 44smkn/dedicated
          operator: Equal
          value: sandbox
          effect: NoSchedule
      resources:
        limits:
          memory: 2600Mi
        requests:
          cpu: 650m
          memory: 2600Mi
