name: microservice2-log / test
on:
  push:
    paths:
      - .github/workflows/microservice2--test.yaml
    branches-ignore:
      - main

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.40.1
